// import { Accessibility, AccessibilityMapping } from "../Utilities/Accessibility";

export const FocusMapping =
{
    // ...AccessibilityMapping,
    bgColor: "bg",
    bgOpacity: "bg-opacity",
    borderColor: "border",
    borderOpacity: "border-opacity",
    shadow: "shadow",
    from: "from",
    via: "via",
    to: "to",
    opacity: "opacity",
    outline: "outline",
    placeholderColor: "placeholder",
    placeholderOpacity: "placeholder-opacity",
    ringColor: "ring",
    ringOffset: "ring-offset",
    ringOffsetColor: "ring-offset",
    ringOpacity: "ring-opacity",
    ringWidth: "ring",
    rotate: "rotate",
    rotateN: "-rotate",
    scale: "scale",
    scaleX: "scale-x",
    scaleY: "scale-y",
    skewX: "skew-x",
    skewXN: "-skew-x",
    skewY: "skew-y",
    skewYN: "-skew-y",
    textColor: "text",
    textDecoration: "",
    textOpacity: "text-opacity",
    translateX: "translate-x",
    translateXN: "-translate-x",
    translateY: "translate-y",
    translateYN: "-translate-y",
    z: "z",
}
