export default interface ThemeColors
{
  transparent: string,
  current: string,

  "black-alpha-100": string,
  "black-alpha-95": string,
  "black-alpha-90": string,
  "black-alpha-85": string,
  "black-alpha-80": string,
  "black-alpha-75": string,
  "black-alpha-70": string,
  "black-alpha-65": string,
  "black-alpha-60": string,
  "black-alpha-55": string,
  "black-alpha-50": string,
  "black-alpha-45": string,
  "black-alpha-40": string,
  "black-alpha-35": string,
  "black-alpha-30": string,
  "black-alpha-25": string,
  "black-alpha-20": string,
  "black-alpha-15": string,
  "black-alpha-10": string,
  "black-alpha-05": string,
  "black-alpha-0": string,

  "white-alpha-100": string,
  "white-alpha-95": string,
  "white-alpha-90": string,
  "white-alpha-85": string,
  "white-alpha-80": string,
  "white-alpha-75": string,
  "white-alpha-70": string,
  "white-alpha-65": string,
  "white-alpha-60": string,
  "white-alpha-55": string,
  "white-alpha-50": string,
  "white-alpha-45": string,
  "white-alpha-40": string,
  "white-alpha-35": string,
  "white-alpha-30": string,
  "white-alpha-25": string,
  "white-alpha-20": string,
  "white-alpha-15": string,
  "white-alpha-10": string,
  "white-alpha-05": string,
  "white-alpha-0": string
}
