import { BorderWidth, Color, Opacity, Outline } from "../../CSSTypes";

export interface Focus
{
  bgColor?: Color,
  bgOpacity?: Opacity,
  border?: true | false | BorderWidth,
  borderT?: true | false | BorderWidth,
  borderB?: true | false | BorderWidth,
  borderS?: true | false | BorderWidth,
  borderE?: true | false | BorderWidth,
  borderColor?: Color,
  borderTColor?: false | Color,
  borderBColor?: false | Color,
  borderSColor?: false | Color,
  borderEColor?: false | Color,
  borderOpacity?: Opacity,
  // shadow?: true | false | "sm" | Breakpoints | "inner" | "none",
  // from?: string,
  // via?: string,
  // to?: string,
  opacity?:Opacity,
  outline?: false | Outline,
  outlineColor: false | Color,
  outlineOpacity: false | Opacity,
  outlineOffset: true | false | BorderWidth,
  // placeholderColor?: string,
  // placeholderOpacity?: Opacity,
  ring?: true | false | BorderWidth,
  ringColor?: string,
  ringInset?: true | false,
  ringOffset?: true | false | BorderWidth,
  ringOffsetColor?: false | Color;
  // rotate?: "0" | "1" | "2" | "2" | "6" | "12" | "45" | "90" | "180";
  // scale?: ScalingScale,
  // scaleX?: ScalingScale,
  // scaleY?: ScalingScale,
  // skewX?: "0" | "1" | "2" | "2" | "6" | "12",
  // skewY?: "0" | "1" | "2" | "2" | "6" | "12",
  textColor?: Color,
  // textDecoration?: "underline" | "line-through" | "no-underline",
  // textOpacity?: Opacity,
  // translateX?: SpacingScale | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "full",
  // translateY?: SpacingScale | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "full",
  // z?: "0" | "10" | "20" | "30" | "40" | "50" | "auto"
}
